# Generated by Django 6.0.6 on 2026-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_fees', models.IntegerField()),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_number', models.BigIntegerField()),
                ('doctor_image', models.ImageField(upload_to='')),
                ('doctor_dept', models.CharField(max_length=200)),
            ],
        ),
    ]
